#!/usr/bin/env python
#encoding: utf-8
import socket

hostname = socket.gethostname()

if hostname == "Precision-Tower-5810": #linux 服务器
    CWD = "/home/dejian/end-to-end-discourse-parser"
    GOOGLE_WORD2VEC_PATH = "/home/dejian/data/word2vec/GoogleNews/GoogleNews-vectors-negative300.bin"
    BLLIP_WORD2VEC_PATH = "/home/dejian/data/BLLIP_parsed/bllip.vectors.bin"
    ZH_WORD2VEC_PATH = "/home/dejian/data/word2vec/zh-Gigaword-300.txt"
else:   # windows
    CWD = "D:/PY/Pycode/project/end-to-end-discourse-parser"
    GOOGLE_WORD2VEC_PATH = "D:/data/word2vec/GoogleNews/GoogleNews-vectors-negative300.bin"
    BLLIP_WORD2VEC_PATH = "D:/data/BLLIP_parsed/bllip.vectors.bin"
    ZH_WORD2VEC_PATH = "D:/data/word2vec/zh-Gigaword-300.txt"
    GLOVE_PATH="D:/data/glove.840B.300d/glove.840B.300d.txt"


DATA_PATH = CWD + "/data"
RECORD_PATH = CWD + "/record"

dict_sense_to_label = {
    "Comparison": 0,
    "Contingency": 1,
    "Expansion": 2,
    "Temporal": 3,
    # "EntRel": 4
}
dict_label_to_sense = {
    0: "Comparison",
    1: "Contingency",
    2: "Expansion",
    3: "Temporal",
    # 4: "EntRel"
}


dict_conll_sense_to_label = {
    'Temporal.Asynchronous.Precedence': 0,
    'Temporal.Asynchronous.Succession': 1,
    'Temporal.Synchrony': 2,
    'Contingency.Cause.Reason': 3,
    'Contingency.Cause.Result': 4,
    'Contingency.Condition': 5,
    'Comparison.Contrast': 6,
    'Comparison.Concession': 7,
    'Expansion.Conjunction': 8,
    'Expansion.Instantiation': 9,
    'Expansion.Restatement': 10,
    'Expansion.Alternative': 11,
    'Expansion.Alternative.Chosen alternative': 12,
    'Expansion.Exception': 13,
    'EntRel': 14,
}

dict_conll_label_to_sense = {
    0: 'Temporal.Asynchronous.Precedence',
    1: 'Temporal.Asynchronous.Succession',
    2: 'Temporal.Synchrony',
    3: 'Contingency.Cause.Reason',
    4: 'Contingency.Cause.Result',
    5: 'Contingency.Condition',
    6: 'Comparison.Contrast',
    7: 'Comparison.Concession',
    8: 'Expansion.Conjunction',
    9: 'Expansion.Instantiation',
    10: 'Expansion.Restatement',
    11: 'Expansion.Alternative',
    12: 'Expansion.Alternative.Chosen alternative',
    13: 'Expansion.Exception',
    14: 'EntRel',
}


dict_connective_to_label = {
    'accordingly': 0,
    'additionally': 1,
    'after': 2,
    'afterward': 3,
    'afterwards': 4,
    'also': 5,
    'alternatively': 6,
    'although': 7,
    'and': 8,
    'as': 9,
    'as a result': 10,
    'as an alternative': 11,
    'as if': 12,
    'as long as': 13,
    'as soon as': 14,
    'as though': 15,
    'as well': 16,
    'because': 17,
    'before': 18,
    'besides': 19,
    'but': 20,
    'by comparison': 21,
    'by contrast': 22,
    'by then': 23,
    'consequently': 24,
    'conversely': 25,
    'earlier': 26,
    'either or': 27,
    'else': 28,
    'except': 29,
    'finally': 30,
    'for example': 31,
    'for instance': 32,
    'further': 33,
    'furthermore': 34,
    'hence': 35,
    'however': 36,
    'if': 37,
    'if and when': 38,
    'if then': 39,
    'in addition': 40,
    'in contrast': 41,
    'in fact': 42,
    'in other words': 43,
    'in particular': 44,
    'in short': 45,
    'in sum': 46,
    'in the end': 47,
    'in turn': 48,
    'indeed': 49,
    'insofar as': 50,
    'instead': 51,
    'later': 52,
    'lest': 53,
    'likewise': 54,
    'meantime': 55,
    'meanwhile': 56,
    'moreover': 57,
    'much as': 58,
    'neither nor': 59,
    'nevertheless': 60,
    'next': 61,
    'nonetheless': 62,
    'nor': 63,
    'now that': 64,
    'on the contrary': 65,
    'on the other hand': 66,
    'once': 67,
    'or': 68,
    'otherwise': 69,
    'overall': 70,
    'plus': 71,
    'previously': 72,
    'rather': 73,
    'regardless': 74,
    'separately': 75,
    'similarly': 76,
    'simultaneously': 77,
    'since': 78,
    'so': 79,
    'so that': 80,
    'specifically': 81,
    'still': 82,
    'then': 83,
    'thereafter': 84,
    'thereby': 85,
    'therefore': 86,
    'though': 87,
    'thus': 88,
    'till': 89,
    'ultimately': 90,
    'unless': 91,
    'until': 92,
    'when': 93,
    'when and if': 94,
    'whereas': 95,
    'while': 96,
    'yet': 97,
}

dict_label_to_connective = {
    0: 'accordingly',
    1: 'additionally',
    2: 'after',
    3: 'afterward',
    4: 'afterwards',
    5: 'also',
    6: 'alternatively',
    7: 'although',
    8: 'and',
    9: 'as',
    10: 'as a result',
    11: 'as an alternative',
    12: 'as if',
    13: 'as long as',
    14: 'as soon as',
    15: 'as though',
    16: 'as well',
    17: 'because',
    18: 'before',
    19: 'besides',
    20: 'but',
    21: 'by comparison',
    22: 'by contrast',
    23: 'by then',
    24: 'consequently',
    25: 'conversely',
    26: 'earlier',
    27: 'either or',
    28: 'else',
    29: 'except',
    30: 'finally',
    31: 'for example',
    32: 'for instance',
    33: 'further',
    34: 'furthermore',
    35: 'hence',
    36: 'however',
    37: 'if',
    38: 'if and when',
    39: 'if then',
    40: 'in addition',
    41: 'in contrast',
    42: 'in fact',
    43: 'in other words',
    44: 'in particular',
    45: 'in short',
    46: 'in sum',
    47: 'in the end',
    48: 'in turn',
    49: 'indeed',
    50: 'insofar as',
    51: 'instead',
    52: 'later',
    53: 'lest',
    54: 'likewise',
    55: 'meantime',
    56: 'meanwhile',
    57: 'moreover',
    58: 'much as',
    59: 'neither nor',
    60: 'nevertheless',
    61: 'next',
    62: 'nonetheless',
    63: 'nor',
    64: 'now that',
    65: 'on the contrary',
    66: 'on the other hand',
    67: 'once',
    68: 'or',
    69: 'otherwise',
    70: 'overall',
    71: 'plus',
    72: 'previously',
    73: 'rather',
    74: 'regardless',
    75: 'separately',
    76: 'similarly',
    77: 'simultaneously',
    78: 'since',
    79: 'so',
    80: 'so that',
    81: 'specifically',
    82: 'still',
    83: 'then',
    84: 'thereafter',
    85: 'thereby',
    86: 'therefore',
    87: 'though',
    88: 'thus',
    89: 'till',
    90: 'ultimately',
    91: 'unless',
    92: 'until',
    93: 'when',
    94: 'when and if',
    95: 'whereas',
    96: 'while',
    97: 'yet',
}